import syltherineImage from "url:../img/product/syltherine.png";
import leviosaImage from "url:../img/product/leviosa edt.png";
import lolitaImage from "url:../img/product/Lolita.png";
import RespiraImage from "url:../img/product/Respira.png";
import GrifoImage from "url:../img/product/grifo.png";
import PingkyImage from "url:../img/product/pingky.png";
import MuggoImage from "url:../img/product/muggo.png";
import pottyImage from "url:../img/product/potty.png";

import sliderImage1 from "url:../img/slider/slide1.png";
import sliderImage2 from "url:../img/slider/slide2.png";
import sliderImage3 from "url:../img/slider/slide3.png";
import sliderImage4 from "url:../img/slider/slide4.png";

import tabbarImage1 from "url:../img/Group 106.png";
import tabbarImage2 from "url:../img/Group 107.png";

export const CURRENCY_UNIT = "USD";
export const LANG = "en-US";

export const products = [
  {
    id: 1,
    name: "syltherine",
    description: "Stylish caffe chair",
    sizes: ["S", "M", "L"],
    colors: ["Red", "Green", "Blue"],
    price: 250,
    discount: 30,
    imageUrl: syltherineImage,
  },
  {
    id: 2,
    name: "Leviosa",
    description: "Stylish caffe chair",
    sizes: ["S", "M", "L"],
    colors: ["Red", "Green", "Blue"],
    price: 250,
    discount: "",
    imageUrl: leviosaImage,
  },
  {
    id: 3,
    name: "Lolita",
    description: "Luxury big sofa",
    sizes: ["S", "M", "L"],
    colors: ["Red", "Green", "Blue"],
    price: 1400,
    discount: 50,
    imageUrl: lolitaImage,
  },
  {
    id: 4,
    name: "Respira",
    description: "Outdoor bar table and stolde",
    sizes: ["S", "M", "L"],
    colors: ["Red", "Green", "Blue"],
    price: 500,
    discount: "",
    imageUrl: RespiraImage,
    new: true,
  },
  {
    id: 5,
    name: "Griffo",
    description: "Night Lamp",
    sizes: ["S", "M", "L"],
    colors: ["Red", "green", "Blue"],
    price: 150,
    discount: "",
    imageUrl: GrifoImage,
    new: true,
  },
  {
    id: 6,
    name: "pingky",
    description: "cute bed set",
    sizes: ["S", "M", "L"],
    colors: ["Red", "green", "Blue"],
    price: 700,
    discount: "",
    imageUrl: PingkyImage,
  },
  {
    id: 7,
    name: "moggo",
    description: " small mug ",
    sizes: ["S", "M", "L"],
    colors: ["Red", "green", "Blue"],
    price: 100,
    discount: "",
    imageUrl: MuggoImage,
  },
  {
    id: 8,
    name: "potty",
    description: " minimalist sofa",
    sizes: ["S", "M", "L"],
    colors: ["Red", "green", "Blue"],
    price: 500,
    discount: 50,
    imageUrl: pottyImage,
  },
];

export const fullProducts = [
  {
    id: 1,
    name: "Syltherine Chair",
    description:
      "Modern and stylish caffe chair perfect for any contemporary space.",
    sizes: ["S", "M", "L"],
    colors: ["Red", "Green", "Blue"],
    price: 250,
    discount: 30,
    imageUrl: syltherineImage,
  },
  {
    id: 2,
    name: "Leviosa Chair",
    description: "Elegant caffe chair with a sleek design and sturdy build.",
    sizes: ["S", "M", "L"],
    colors: ["Red", "Green", "Blue"],
    price: 250,
    discount: "",
    imageUrl: leviosaImage,
  },
  {
    id: 3,
    name: "Lolita Sofa",
    description: "Luxury large sofa, perfect for spacious living rooms.",
    sizes: ["S", "M", "L"],
    colors: ["Red", "Green", "Blue"],
    price: 1400,
    discount: 50,
    imageUrl: lolitaImage,
  },
  {
    id: 4,
    name: "Respira Outdoor Table",
    description:
      "Stylish outdoor bar table and stools, ideal for patios and gardens.",
    sizes: ["S", "M", "L"],
    colors: ["Red", "Green", "Blue"],
    price: 500,
    discount: "",
    imageUrl: RespiraImage,
    new: true,
  },
  {
    id: 5,
    name: "Griffo Night Lamp",
    description:
      "Contemporary night lamp with an elegant and minimalistic design.",
    sizes: ["S", "M", "L"],
    colors: ["Red", "Green", "Blue"],
    price: 150,
    discount: "",
    imageUrl: GrifoImage,
    new: true,
  },
  {
    id: 6,
    name: "Pingky Bed Set",
    description: "A cute and comfortable bed set perfect for kids and teens.",
    sizes: ["S", "M", "L"],
    colors: ["Red", "Green", "Blue"],
    price: 700,
    discount: "",
    imageUrl: PingkyImage,
  },
  {
    id: 7,
    name: "Moggo Mug",
    description: "A small, stylish mug for your coffee or tea needs.",
    sizes: ["S", "M", "L"],
    colors: ["Red", "Green", "Blue"],
    price: 100,
    discount: "",
    imageUrl: MuggoImage,
  },
  {
    id: 8,
    name: "Potty Minimalist Sofa",
    description: "Comfortable minimalist sofa, great for modern interiors.",
    sizes: ["S", "M", "L"],
    colors: ["Red", "Green", "Blue"],
    price: 500,
    discount: 50,
    imageUrl: pottyImage,
  },
  {
    id: 9,
    name: "Orion Coffee Table",
    description: "A sleek and modern coffee table made from high-quality wood.",
    sizes: ["S", "M", "L"],
    colors: ["Black", "White", "Brown"],
    price: 320,
    discount: 15,
    imageUrl: syltherineImage,
  },
  {
    id: 10,
    name: "Luna Bookshelf",
    description:
      "A tall and elegant bookshelf with multiple shelves for storage.",
    sizes: ["S", "M", "L"],
    colors: ["White", "Walnut", "Black"],
    price: 750,
    discount: 20,
    imageUrl: leviosaImage,
  },
  {
    id: 11,
    name: "Aurora Dining Set",
    description: "Luxurious dining set with a large table and six chairs.",
    sizes: ["S", "M", "L"],
    colors: ["Gray", "Beige", "White"],
    price: 1800,
    discount: 40,
    imageUrl: lolitaImage,
  },
  {
    id: 12,
    name: "Celestia Armchair",
    description: "A comfortable armchair with a plush feel and modern look.",
    sizes: ["S", "M", "L"],
    colors: ["Yellow", "Navy", "Green"],
    price: 650,
    discount: "",
    imageUrl: RespiraImage,
  },
  {
    id: 13,
    name: "Vega Floor Lamp",
    description:
      "A modern floor lamp perfect for illuminating any living space.",
    sizes: ["S", "M", "L"],
    colors: ["Black", "Gold", "Silver"],
    price: 200,
    discount: 5,
    imageUrl: GrifoImage,
  },
  {
    id: 14,
    name: "Nova Bed Frame",
    description: "A sturdy and stylish bed frame made of solid wood.",
    sizes: ["S", "M", "L"],
    colors: ["Oak", "Walnut", "Black"],
    price: 1100,
    discount: 25,
    imageUrl: PingkyImage,
  },
  {
    id: 15,
    name: "Atlas Bar Stool",
    description:
      "A modern bar stool with a comfortable seat and adjustable height.",
    sizes: ["S", "M", "L"],
    colors: ["Black", "Red", "Blue"],
    price: 180,
    discount: "",
    imageUrl: MuggoImage,
  },
  {
    id: 16,
    name: "Comet Desk",
    description: "A compact desk perfect for home offices or study rooms.",
    sizes: ["S", "M", "L"],
    colors: ["White", "Brown", "Black"],
    price: 450,
    discount: 30,
    imageUrl: pottyImage,
  },
  {
    id: 17,
    name: "Apollo Sofa",
    description: "A large, comfortable sofa with a minimalist design.",
    sizes: ["S", "M", "L"],
    colors: ["Gray", "Blue", "Beige"],
    price: 1300,
    discount: 15,
    imageUrl: syltherineImage,
  },
  {
    id: 18,
    name: "Hermes Side Table",
    description: "A stylish side table with a marble top and metal legs.",
    sizes: ["S", "M", "L"],
    colors: ["Black", "White", "Gold"],
    price: 300,
    discount: 10,
    imageUrl: leviosaImage,
  },
  {
    id: 19,
    name: "Zephyr Lounge Chair",
    description: "A chic lounge chair with a cozy feel and modern lines.",
    sizes: ["S", "M", "L"],
    colors: ["Blue", "Green", "Gray"],
    price: 850,
    discount: 20,
    imageUrl: lolitaImage,
  },
  {
    id: 20,
    name: "Helios Ceiling Light",
    description: "An industrial-style ceiling light with exposed bulbs.",
    sizes: ["S", "M", "L"],
    colors: ["Black", "Brass", "Copper"],
    price: 550,
    discount: "",
    imageUrl: RespiraImage,
  },
  {
    id: 21,
    name: "Neptune Mirror",
    description: "A large round mirror with a minimalist frame.",
    sizes: ["S", "M", "L"],
    colors: ["Silver", "Gold", "Black"],
    price: 250,
    discount: 5,
    imageUrl: GrifoImage,
  },
  {
    id: 22,
    name: "Orpheus Cabinet",
    description: "A sleek storage cabinet with multiple drawers.",
    sizes: ["S", "M", "L"],
    colors: ["Black", "Brown", "White"],
    price: 700,
    discount: 10,
    imageUrl: PingkyImage,
  },
  {
    id: 23,
    name: "Aether Coffee Table",
    description: "A modern glass-top coffee table with chrome legs.",
    sizes: ["S", "M", "L"],
    colors: ["Clear", "Black", "White"],
    price: 400,
    discount: "",
    imageUrl: MuggoImage,
  },
  {
    id: 24,
    name: "Phoenix Recliner",
    description: "A luxury recliner chair with adjustable settings.",
    sizes: ["S", "M", "L"],
    colors: ["Black", "Gray", "Brown"],
    price: 1200,
    discount: 35,
    imageUrl: pottyImage,
  },
  {
    id: 25,
    name: "Ganymede Bedside Table",
    description: "A small, functional bedside table with a drawer.",
    sizes: ["S", "M", "L"],
    colors: ["White", "Black", "Gray"],
    price: 300,
    discount: 15,
    imageUrl: syltherineImage,
  },
  {
    id: 26,
    name: "Jupiter Dining Chair",
    description:
      "A stylish dining chair with wooden legs and a cushioned seat.",
    sizes: ["S", "M", "L"],
    colors: ["Black", "White", "Gray"],
    price: 220,
    discount: 10,
    imageUrl: leviosaImage,
  },
  {
    id: 27,
    name: "Cosmos Bed Frame",
    description: "A wooden bed frame with a minimalist and sturdy design.",
    sizes: ["S", "M", "L"],
    colors: ["Oak", "Walnut", "Black"],
    price: 1200,
    discount: 20,
    imageUrl: lolitaImage,
  },
  {
    id: 28,
    name: "Pluto Nightstand",
    description: "A modern nightstand with a drawer and open shelf.",
    sizes: ["S", "M", "L"],
    colors: ["Black", "White", "Gray"],
    price: 180,
    discount: "",
    imageUrl: RespiraImage,
  },
  {
    id: 29,
    name: "Aurora TV Stand",
    description:
      "A sleek and modern TV stand with multiple shelves for storage.",
    sizes: ["S", "M", "L"],
    colors: ["Black", "White", "Brown"],
    price: 600,
    discount: 25,
    imageUrl: GrifoImage,
  },
  {
    id: 30,
    name: "Solis Wardrobe",
    description:
      "A spacious wardrobe with sliding doors and multiple compartments.",
    sizes: ["S", "M", "L"],
    colors: ["White", "Gray", "Black"],
    price: 1400,
    discount: 40,
    imageUrl: PingkyImage,
  },
  {
    id: 31,
    name: "Titanium Sofa",
    description: "A large, comfortable sofa with a modern, minimalist design.",
    sizes: ["S", "M", "L"],
    colors: ["Gray", "Navy", "Beige"],
    price: 1350,
    discount: 25,
    imageUrl: MuggoImage,
  },
  {
    id: 32,
    name: "Venus Floor Lamp",
    description: "A contemporary floor lamp with adjustable brightness.",
    sizes: ["S", "M", "L"],
    colors: ["Gold", "Black", "Silver"],
    price: 200,
    discount: 10,
    imageUrl: pottyImage,
  },
  {
    id: 33,
    name: "Mars Coffee Table",
    description: "A stylish coffee table with a wooden top and metal legs.",
    sizes: ["S", "M", "L"],
    colors: ["Black", "White", "Walnut"],
    price: 450,
    discount: 15,
    imageUrl: syltherineImage,
  },
  {
    id: 34,
    name: "Pandora Ottoman",
    description: "A comfortable ottoman that doubles as extra seating.",
    sizes: ["S", "M", "L"],
    colors: ["Gray", "Blue", "Beige"],
    price: 200,
    discount: "",
    imageUrl: leviosaImage,
  },
  {
    id: 35,
    name: "Themis Console Table",
    description: "A modern console table with a glass top and metal frame.",
    sizes: ["S", "M", "L"],
    colors: ["Black", "Gold", "Silver"],
    price: 500,
    discount: 15,
    imageUrl: lolitaImage,
  },
  {
    id: 36,
    name: "Io Dining Set",
    description: "A compact dining set with a round table and four chairs.",
    sizes: ["S", "M", "L"],
    colors: ["White", "Black", "Gray"],
    price: 800,
    discount: 20,
    imageUrl: RespiraImage,
  },
  {
    id: 37,
    name: "Medusa Mirror",
    description: "A large decorative mirror with an ornate frame.",
    sizes: ["S", "M", "L"],
    colors: ["Gold", "Silver", "Black"],
    price: 450,
    discount: "",
    imageUrl: GrifoImage,
  },
  {
    id: 38,
    name: "Oberon Sofa",
    description: "A luxury sectional sofa with a modern design.",
    sizes: ["S", "M", "L"],
    colors: ["Gray", "Blue", "Beige"],
    price: 1600,
    discount: 30,
    imageUrl: PingkyImage,
  },
  {
    id: 39,
    name: "Triton Bed",
    description: "A king-sized bed with a plush headboard and modern frame.",
    sizes: ["S", "M", "L"],
    colors: ["White", "Gray", "Black"],
    price: 1800,
    discount: 40,
    imageUrl: MuggoImage,
  },
  {
    id: 40,
    name: "Atlas Office Chair",
    description:
      "A comfortable and adjustable office chair with lumbar support.",
    sizes: ["S", "M", "L"],
    colors: ["Black", "Gray", "Blue"],
    price: 350,
    discount: "",
    imageUrl: pottyImage,
  },
  {
    id: 41,
    name: "Hestia Coffee Table",
    description: "A coffee table with a marble top and metal legs.",
    sizes: ["S", "M", "L"],
    colors: ["White", "Black", "Gold"],
    price: 600,
    discount: 20,
    imageUrl: syltherineImage,
  },
  {
    id: 42,
    name: "Persephone Lounge Chair",
    description: "A luxurious lounge chair with plush cushioning.",
    sizes: ["S", "M", "L"],
    colors: ["Gray", "Blue", "Green"],
    price: 900,
    discount: 35,
    imageUrl: leviosaImage,
  },
  {
    id: 43,
    name: "Olympus Dining Table",
    description: "A large dining table with a glass top and metal legs.",
    sizes: ["S", "M", "L"],
    colors: ["Black", "White", "Silver"],
    price: 1200,
    discount: 30,
    imageUrl: lolitaImage,
  },
  {
    id: 44,
    name: "Zeus Recliner",
    description:
      "A modern recliner chair with adjustable features and comfort.",
    sizes: ["S", "M", "L"],
    colors: ["Black", "Brown", "Gray"],
    price: 1100,
    discount: "",
    imageUrl: RespiraImage,
  },
  {
    id: 45,
    name: "Kronos Bedside Table",
    description: "A small bedside table with drawers and a sleek design.",
    sizes: ["S", "M", "L"],
    colors: ["White", "Black", "Gray"],
    price: 320,
    discount: 10,
    imageUrl: GrifoImage,
  },
  {
    id: 46,
    name: "Hyperion Wardrobe",
    description: "A large wardrobe with sliding doors and ample storage space.",
    sizes: ["S", "M", "L"],
    colors: ["White", "Gray", "Black"],
    price: 1500,
    discount: 20,
    imageUrl: PingkyImage,
  },
  {
    id: 47,
    name: "Helios Floor Lamp",
    description: "A modern floor lamp with an adjustable neck and bright LED.",
    sizes: ["S", "M", "L"],
    colors: ["Black", "Gold", "Silver"],
    price: 180,
    discount: 5,
    imageUrl: MuggoImage,
  },
  {
    id: 48,
    name: "Poseidon Armchair",
    description: "A comfortable armchair with a modern design.",
    sizes: ["S", "M", "L"],
    colors: ["Gray", "Blue", "Green"],
    price: 800,
    discount: 15,
    imageUrl: pottyImage,
  },
  {
    id: 49,
    name: "Athena Bookshelf",
    description: "A tall bookshelf with ample space for books and decor.",
    sizes: ["S", "M", "L"],
    colors: ["White", "Black", "Gray"],
    price: 900,
    discount: 25,
    imageUrl: syltherineImage,
  },
  {
    id: 50,
    name: "Hephaestus Desk",
    description:
      "A sturdy desk with ample workspace for office or study needs.",
    sizes: ["S", "M", "L"],
    colors: ["Black", "White", "Walnut"],
    price: 700,
    discount: 15,
    imageUrl: leviosaImage,
  },
];

export const slides = [
  {
    title: "bedroom",
    description: "inner peace",
    imageUrl: sliderImage1,
  },
  {
    title: "bedroom",
    description: "inner peace",
    imageUrl: sliderImage2,
  },
  {
    title: "bedroom",
    description: "inner peace",
    imageUrl: sliderImage3,
  },
  {
    title: "bedroom",
    description: "inner peace",
    imageUrl: sliderImage4,
  },
];

export const TabbarTabs = [
  {
    title: "description",
    description: {
      paragraphes: [
        `Embodying the raw, wayward spirit of rock ‘n’ roll, the Kilburn portable active stereo speaker takes the unmistakable look and sound of Marshall, unplugs the chords, and takes the show on the road`,
        `Weighing in under 7 pounds, the Kilburn is a lightweight piece of vintage styled engineering. Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound that is both articulate and pronounced. The analogue knobs allow you to fine tune the controls to your personal preferences while the guitar-influenced leather strap enables easy and stylish travel.`,
      ],
      images: [tabbarImage1, tabbarImage2],
    },
  },
  {
    title: "aditional information",
    description: {
      paragraphes: [
        `Embodying the raw, wayward spirit of rock ‘n’ roll, the Kilburn portable active stereo speaker takes the unmistakable look and sound of Marshall, unplugs the chords, and takes the show on the road`,
        `Weighing in under 7 pounds, the Kilburn is a lightweight piece of vintage styled engineering. Setting the bar as one of the loudest speakers in its class, the Kilburn is a compact, stout-hearted hero with a well-balanced audio which boasts a clear midrange and extended highs for a sound that is both articulate and pronounced. The analogue knobs allow you to fine tune the controls to your personal preferences while the guitar-influenced leather strap enables easy and stylish travel.`,
      ],
    },
  },
];
